export enum TapoErrorCode {
  AES_DECODE_FAIL = -1005,
  REQUEST_LENGTH_ERROR = -1006,
  INVALID_REQUEST_PARAMS = -1008,
  RATE_LIMIT_EXCEEDED = -1301,
  SESSION_PARAMS_ERROR = -1101,
  INVALID_PUBLIC_KEY_LENGTH = -1010,
  INVALID_TERMINAL_UUID = -1012,
  INVALID_CREDENTIALS = -1501,
  TRANSPORT_NOT_AVAILABLE = -1002,
  MALFORMED_JSON_REQUEST = -1003,
  API_RATE_LIMIT_EXCEEDED = -20004,
  MISSING_CREDENTIALS = -20104,
  INCORRECT_EMAIL_OR_PASSWORD = -20601,
  CLOUD_TOKEN_EXPIRED = -20675,
  NULL_TRANSPORT_ERROR = 1000,
  COMMAND_CANCEL_ERROR = 1001,
  TRANSPORT_NOT_AVAILABLE_ERROR = 1002,
  KLAP_PROTOCOL_SUPPORTED = 1003,
  HANDSHAKE_FAILED = 1100,
  LOGIN_FAILED = 1111,
  HTTP_TRANSPORT_ERROR = 1112,
  MULTIREQUEST_FAILED = 1200,
  SESSION_TIMEOUT = 9999,
}

export const TapoErrorMessages: Record<number, string> = {
  [TapoErrorCode.AES_DECODE_FAIL]: 'AES Decode Fail',
  [TapoErrorCode.REQUEST_LENGTH_ERROR]: 'Request length error',
  [TapoErrorCode.INVALID_REQUEST_PARAMS]: 'Invalid request params',
  [TapoErrorCode.RATE_LIMIT_EXCEEDED]: 'Rate limit exceeded',
  [TapoErrorCode.SESSION_PARAMS_ERROR]: 'Session params error',
  [TapoErrorCode.INVALID_PUBLIC_KEY_LENGTH]: 'Invalid public key length',
  [TapoErrorCode.INVALID_TERMINAL_UUID]: 'Invalid terminal UUID',
  [TapoErrorCode.INVALID_CREDENTIALS]: 'Invalid credentials',
  [TapoErrorCode.TRANSPORT_NOT_AVAILABLE]: 'Transport not available error',
  [TapoErrorCode.MALFORMED_JSON_REQUEST]: 'Malformed json request',
  [TapoErrorCode.API_RATE_LIMIT_EXCEEDED]: 'API rate limit exceeded',
  [TapoErrorCode.MISSING_CREDENTIALS]: 'Missing credentials',
  [TapoErrorCode.INCORRECT_EMAIL_OR_PASSWORD]: 'Incorrect email or password',
  [TapoErrorCode.CLOUD_TOKEN_EXPIRED]: 'Cloud token expired or invalid',
  [TapoErrorCode.NULL_TRANSPORT_ERROR]: 'Null transport error',
  [TapoErrorCode.COMMAND_CANCEL_ERROR]: 'Command cancel error',
  [TapoErrorCode.TRANSPORT_NOT_AVAILABLE_ERROR]: 'Transport not available error',
  [TapoErrorCode.KLAP_PROTOCOL_SUPPORTED]: 'Device supports KLAP protocol - Legacy login not supported',
  [TapoErrorCode.HANDSHAKE_FAILED]: 'Handshake failed',
  [TapoErrorCode.LOGIN_FAILED]: 'Login failed',
  [TapoErrorCode.HTTP_TRANSPORT_ERROR]: 'Http transport error',
  [TapoErrorCode.MULTIREQUEST_FAILED]: 'Multirequest failed',
  [TapoErrorCode.SESSION_TIMEOUT]: 'Session Timeout',
};
